appenders:
  my_stdout:
    kind: console
    encoder:
      pattern: "{d(%Y-%m-%d %H:%M:%S%.3f Z%z)} - {h({l})}: {M}: {f}.{L} - PID {P} Thread {T} {I} {n}{m}{n}"
  my_file_logger:
    kind: rolling_file
    path: "log/my.log"
    encoder:
      pattern: "{d(%Y-%m-%d %H:%M:%S%.3f Z%z)} - {l}: {M}: {f}.{L} - PID {P} Thread {T} {I} {n}{m}{n}"
    policy:
      trigger:
        kind: size
        limit: 3Mb
      roller:
        kind: fixed_window
        base: 1
        count: 5
        pattern: "log/my{}.gz"
root:
  level: trace
  appenders:
    - my_stdout
    - my_file_logger
